// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_main
extern void ui_main_screen_init(void);
extern void ui_main_screen_destroy(void);
extern lv_obj_t * ui_main;
extern lv_obj_t * ui_NavBar;
extern lv_obj_t * ui_clockContainer1;
extern lv_obj_t * ui_TrenutniCas;
extern lv_obj_t * ui_StUcilnice;
extern lv_obj_t * ui_clockContainer2;
extern lv_obj_t * ui_datum;
extern lv_obj_t * ui_timetableContainer;
extern lv_obj_t * ui_lessonBox;
extern lv_obj_t * ui_infoContainer2;
extern lv_obj_t * ui_circle2;
extern lv_obj_t * ui_StUre;
extern lv_obj_t * ui_moreInfoContainer2;
extern lv_obj_t * ui_topInfo1;
extern lv_obj_t * ui_Predmet;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Razred;
extern lv_obj_t * ui_Profesor;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_UraPredmeta;
extern lv_obj_t * ui_lessonBox1;
extern lv_obj_t * ui_infoContainer1;
extern lv_obj_t * ui_circle1;
extern lv_obj_t * ui_StUre1;
extern lv_obj_t * ui_moreInfoContainer1;
extern lv_obj_t * ui_topInfo2;
extern lv_obj_t * ui_Predmet1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Razred1;
extern lv_obj_t * ui_Profesor1;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_UraPredmeta1;
extern lv_obj_t * ui_lessonBox2;
extern lv_obj_t * ui_infoContainer3;
extern lv_obj_t * ui_circle3;
extern lv_obj_t * ui_StUre2;
extern lv_obj_t * ui_moreInfoContainer3;
extern lv_obj_t * ui_topInfo3;
extern lv_obj_t * ui_Predmet2;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Razred2;
extern lv_obj_t * ui_Profesor2;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_UraPredmeta2;
extern lv_obj_t * ui_lessonBox3;
extern lv_obj_t * ui_infoContainer4;
extern lv_obj_t * ui_circle4;
extern lv_obj_t * ui_StUre3;
extern lv_obj_t * ui_moreInfoContainer4;
extern lv_obj_t * ui_topInfo4;
extern lv_obj_t * ui_Predmet3;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Razred3;
extern lv_obj_t * ui_Profesor3;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_UraPredmeta3;
extern lv_obj_t * ui_lessonBox4;
extern lv_obj_t * ui_infoContainer5;
extern lv_obj_t * ui_circle5;
extern lv_obj_t * ui_StUre4;
extern lv_obj_t * ui_moreInfoContainer5;
extern lv_obj_t * ui_topInfo5;
extern lv_obj_t * ui_Predmet4;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Razred4;
extern lv_obj_t * ui_Profesor4;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_UraPredmeta4;
extern lv_obj_t * ui_lessonBox5;
extern lv_obj_t * ui_infoContainer6;
extern lv_obj_t * ui_circle6;
extern lv_obj_t * ui_StUre5;
extern lv_obj_t * ui_moreInfoContainer6;
extern lv_obj_t * ui_topInfo6;
extern lv_obj_t * ui_Predmet5;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Razred5;
extern lv_obj_t * ui_Profesor5;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_UraPredmeta5;
extern lv_obj_t * ui_lessonBox6;
extern lv_obj_t * ui_infoContainer7;
extern lv_obj_t * ui_circle7;
extern lv_obj_t * ui_StUre6;
extern lv_obj_t * ui_moreInfoContainer7;
extern lv_obj_t * ui_topInfo7;
extern lv_obj_t * ui_Predmet6;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_Razred6;
extern lv_obj_t * ui_Profesor6;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_UraPredmeta6;
extern lv_obj_t * ui_lessonBox7;
extern lv_obj_t * ui_infoContainer8;
extern lv_obj_t * ui_circle8;
extern lv_obj_t * ui_StUre7;
extern lv_obj_t * ui_moreInfoContainer8;
extern lv_obj_t * ui_topInfo8;
extern lv_obj_t * ui_Predmet7;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_Razred7;
extern lv_obj_t * ui_Profesor7;
extern lv_obj_t * ui_Container16;
extern lv_obj_t * ui_UraPredmeta7;
extern lv_obj_t * ui_lessonBox8;
extern lv_obj_t * ui_infoContainer9;
extern lv_obj_t * ui_circle9;
extern lv_obj_t * ui_StUre8;
extern lv_obj_t * ui_moreInfoContainer9;
extern lv_obj_t * ui_topInfo9;
extern lv_obj_t * ui_Predmet8;
extern lv_obj_t * ui_Container17;
extern lv_obj_t * ui_Razred8;
extern lv_obj_t * ui_Profesor8;
extern lv_obj_t * ui_Container18;
extern lv_obj_t * ui_UraPredmeta8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

