// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_startup = NULL;lv_obj_t *ui_Label1 = NULL;
// event funtions

// build funtions

void ui_startup_screen_init(void)
{
ui_startup = lv_obj_create(NULL);
lv_obj_remove_flag( ui_startup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_startup,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_startup, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_bg_color(ui_startup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_startup, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_startup);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -6 );
lv_obj_set_y( ui_Label1, -16 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Povezovanje z omrežjem WIFI...");
lv_obj_set_style_text_font(ui_Label1, &ui_font_h3, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_startup_screen_destroy(void)
{
   if (ui_startup) lv_obj_del(ui_startup);

// NULL screen variables
ui_startup= NULL;
ui_Label1= NULL;

}
