// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_STARTUP_H
#define UI_STARTUP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_startup
extern void ui_startup_screen_init(void);
extern void ui_startup_screen_destroy(void);
extern lv_obj_t *ui_startup;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Spinner1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

