// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_startup_screen_init(void)
{
    ui_startup = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_startup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_startup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_startup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imageContainer = lv_image_create(ui_startup);
    lv_image_set_src(ui_imageContainer, &ui_img_diapozitiv26_png);
    lv_obj_set_width(ui_imageContainer, lv_pct(100));
    lv_obj_set_height(ui_imageContainer, lv_pct(100));
    lv_obj_set_x(ui_imageContainer, -3);
    lv_obj_set_y(ui_imageContainer, -25);
    lv_obj_set_align(ui_imageContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imageContainer, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imageContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_imageContainer, 180);

    ui_Label19 = lv_label_create(ui_startup);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 0);
    lv_obj_set_y(ui_Label19, 429);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Izdelava: Lin Čadež, Maj Mohar");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0x393F39), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &ui_font_P1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Label19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_startup, ui_event_startup, LV_EVENT_ALL, NULL);

}
