// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT lessonBox

lv_obj_t *ui_lessonBox_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_lessonBox;
cui_lessonBox = lv_obj_create(comp_parent);
lv_obj_remove_style_all(cui_lessonBox);
lv_obj_set_height( cui_lessonBox, 100);
lv_obj_set_width( cui_lessonBox, lv_pct(100));
lv_obj_set_x( cui_lessonBox, -186 );
lv_obj_set_y( cui_lessonBox, -325 );
lv_obj_set_flex_flow(cui_lessonBox,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_lessonBox, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( cui_lessonBox, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_lessonBox, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_lessonBox, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_lessonBox, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_lessonBox, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_lessonBox, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_lessonBox, 25, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_infoContainer2;
cui_infoContainer2 = lv_obj_create(cui_lessonBox);
lv_obj_remove_style_all(cui_infoContainer2);
lv_obj_set_width( cui_infoContainer2, 200);
lv_obj_set_height( cui_infoContainer2, 70);
lv_obj_set_align( cui_infoContainer2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_infoContainer2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_infoContainer2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( cui_infoContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_circle2;
cui_circle2 = lv_obj_create(cui_infoContainer2);
lv_obj_remove_style_all(cui_circle2);
lv_obj_set_width( cui_circle2, 40);
lv_obj_set_height( cui_circle2, 40);
lv_obj_set_x( cui_circle2, -20 );
lv_obj_set_y( cui_circle2, 0 );
lv_obj_set_align( cui_circle2, LV_ALIGN_CENTER );
lv_obj_add_state( cui_circle2, LV_STATE_CHECKED );     /// States
lv_obj_remove_flag( cui_circle2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_circle2, 1000, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(cui_circle2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_red);
ui_object_set_themeable_style_property(cui_circle2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_red);

lv_obj_t *cui_StUre;
cui_StUre = lv_label_create(cui_circle2);
lv_obj_set_width( cui_StUre, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_StUre, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_StUre, LV_ALIGN_CENTER );
lv_label_set_text(cui_StUre,"1");
lv_obj_set_style_text_color(cui_StUre, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_StUre, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_StUre, &ui_font_h3, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_moreInfoContainer2;
cui_moreInfoContainer2 = lv_obj_create(cui_infoContainer2);
lv_obj_remove_style_all(cui_moreInfoContainer2);
lv_obj_set_width( cui_moreInfoContainer2, 127);
lv_obj_set_height( cui_moreInfoContainer2, 65);
lv_obj_set_align( cui_moreInfoContainer2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_moreInfoContainer2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(cui_moreInfoContainer2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( cui_moreInfoContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(cui_moreInfoContainer2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(cui_moreInfoContainer2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_topInfo1;
cui_topInfo1 = lv_obj_create(cui_moreInfoContainer2);
lv_obj_remove_style_all(cui_topInfo1);
lv_obj_set_height( cui_topInfo1, 34);
lv_obj_set_width( cui_topInfo1, lv_pct(123));
lv_obj_set_align( cui_topInfo1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_topInfo1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_topInfo1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( cui_topInfo1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(cui_topInfo1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(cui_topInfo1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Predmet;
cui_Predmet = lv_label_create(cui_topInfo1);
lv_obj_set_width( cui_Predmet, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Predmet, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_Predmet, LV_ALIGN_CENTER );
lv_label_set_text(cui_Predmet,"SLO");
ui_object_set_themeable_style_property(cui_Predmet, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_red);
ui_object_set_themeable_style_property(cui_Predmet, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_red);
lv_obj_set_style_text_font(cui_Predmet, &ui_font_h3, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Container1;
cui_Container1 = lv_obj_create(cui_topInfo1);
lv_obj_remove_style_all(cui_Container1);
lv_obj_set_width( cui_Container1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Container1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_Container1, LV_ALIGN_CENTER );
lv_obj_remove_flag( cui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_Container1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(cui_Container1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_red);
ui_object_set_themeable_style_property(cui_Container1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_red);
lv_obj_set_style_pad_left(cui_Container1, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Container1, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Container1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Container1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(cui_Container1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_Container1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Razred;
cui_Razred = lv_label_create(cui_Container1);
lv_obj_set_width( cui_Razred, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Razred, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_Razred, LV_ALIGN_CENTER );
lv_label_set_text(cui_Razred,"G3A");
lv_obj_set_style_text_color(cui_Razred, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_Razred, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_Razred, &ui_font_P1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Profesor;
cui_Profesor = lv_label_create(cui_moreInfoContainer2);
lv_obj_set_width( cui_Profesor, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Profesor, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_Profesor, LV_ALIGN_CENTER );
lv_label_set_text(cui_Profesor,"Aleš Volčini");
ui_object_set_themeable_style_property(cui_Profesor, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_teacherGray);
ui_object_set_themeable_style_property(cui_Profesor, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_teacherGray);
lv_obj_set_style_text_font(cui_Profesor, &ui_font_p, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Container3;
cui_Container3 = lv_obj_create(cui_lessonBox);
lv_obj_remove_style_all(cui_Container3);
lv_obj_set_width( cui_Container3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Container3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_Container3, LV_ALIGN_CENTER );
lv_obj_remove_flag( cui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_UraPredmeta;
cui_UraPredmeta = lv_label_create(cui_Container3);
lv_obj_set_width( cui_UraPredmeta, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_UraPredmeta, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_UraPredmeta, LV_ALIGN_CENTER );
lv_label_set_text(cui_UraPredmeta,"8:00 - 8:45");
lv_obj_set_style_text_letter_space(cui_UraPredmeta, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(cui_UraPredmeta, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_UraPredmeta, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_LESSONBOX_NUM);
children[UI_COMP_LESSONBOX_LESSONBOX] = cui_lessonBox;
children[UI_COMP_LESSONBOX_INFOCONTAINER2] = cui_infoContainer2;
children[UI_COMP_LESSONBOX_INFOCONTAINER2_CIRCLE2] = cui_circle2;
children[UI_COMP_LESSONBOX_INFOCONTAINER2_CIRCLE2_STURE] = cui_StUre;
children[UI_COMP_LESSONBOX_INFOCONTAINER2_MOREINFOCONTAINER2] = cui_moreInfoContainer2;
children[UI_COMP_LESSONBOX_INFOCONTAINER2_MOREINFOCONTAINER2_TOPINFO1] = cui_topInfo1;
children[UI_COMP_LESSONBOX_INFOCONTAINER2_MOREINFOCONTAINER2_TOPINFO1_PREDMET] = cui_Predmet;
children[UI_COMP_LESSONBOX_INFOCONTAINER2_MOREINFOCONTAINER2_TOPINFO1_CONTAINER1] = cui_Container1;
children[UI_COMP_LESSONBOX_INFOCONTAINER2_MOREINFOCONTAINER2_TOPINFO1_CONTAINER1_RAZRED] = cui_Razred;
children[UI_COMP_LESSONBOX_INFOCONTAINER2_MOREINFOCONTAINER2_PROFESOR] = cui_Profesor;
children[UI_COMP_LESSONBOX_CONTAINER3] = cui_Container3;
children[UI_COMP_LESSONBOX_CONTAINER3_URAPREDMETA] = cui_UraPredmeta;
lv_obj_add_event_cb(cui_lessonBox, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_lessonBox, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_lessonBox_create_hook(cui_lessonBox);
return cui_lessonBox; 
}

