// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void startupAnimation_Animation( lv_obj_t *TargetObject, int delay);
void fadeup_Animation( lv_obj_t *TargetObject, int delay);

// SCREEN: ui_main
void ui_main_screen_init(void);
lv_obj_t *ui_main;
lv_obj_t *ui_NavBar;
lv_obj_t *ui_clockContainer1;
lv_obj_t *ui_TrenutniCas;
lv_obj_t *ui_StUcilnice;
lv_obj_t *ui_clockContainer2;
lv_obj_t *ui_datum;
lv_obj_t *ui_timetableContainer;
lv_obj_t *ui_lessonBox1;
lv_obj_t *ui_infoContainer3;
lv_obj_t *ui_circle3;
lv_obj_t *ui_StUre2;
lv_obj_t *ui_moreInfoContainer3;
lv_obj_t *ui_topInfo2;
lv_obj_t *ui_Predmet2;
lv_obj_t *ui_Container4;
lv_obj_t *ui_Razred1;
lv_obj_t *ui_Profesor1;
lv_obj_t *ui_Container5;
lv_obj_t *ui_UraPredmeta2;
lv_obj_t *ui_lessonBoxEmpty;
lv_obj_t *ui_infoContainer1;
lv_obj_t *ui_circle1;
lv_obj_t *ui_StUre1;
lv_obj_t *ui_moreInfoContainer1;
lv_obj_t *ui_Predmet1;
lv_obj_t *ui_Container2;
lv_obj_t *ui_UraPredmeta1;
// CUSTOM VARIABLES

// SCREEN: ui_startup
void ui_startup_screen_init(void);
lv_obj_t *ui_startup;
lv_obj_t *ui_Label19;
lv_obj_t *ui_imageContainer;
lv_obj_t *ui_Spinner1;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_image_dsc_t *ui_imgset_diapozitiv[21] = {&ui_img_diapozitiv1_png, &ui_img_diapozitiv10_png, &ui_img_diapozitiv11_png, &ui_img_diapozitiv12_png, &ui_img_diapozitiv2_png, &ui_img_diapozitiv13_png, &ui_img_diapozitiv3_png, &ui_img_diapozitiv14_png, &ui_img_diapozitiv4_png, &ui_img_diapozitiv15_png, &ui_img_diapozitiv5_png, &ui_img_diapozitiv16_png, &ui_img_diapozitiv6_png, &ui_img_diapozitiv17_png, &ui_img_diapozitiv7_png, &ui_img_diapozitiv18_png, &ui_img_diapozitiv8_png, &ui_img_diapozitiv19_png, &ui_img_diapozitiv20_png, &ui_img_diapozitiv21_png, &ui_img_diapozitiv9_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void startupAnimation_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->imgset = (lv_img_dsc_t **)ui_imgset_diapozitiv;
PropertyAnimation_0_user_data->imgset_size = sizeof(ui_imgset_diapozitiv)/(sizeof(lv_image_dsc_t*));
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1400);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_frame );
lv_anim_set_values(&PropertyAnimation_0, 1, 21 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 200 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 1400);
lv_anim_set_playback_delay(&PropertyAnimation_0, 200);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 200);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_frame );
lv_anim_start(&PropertyAnimation_0);

}
void fadeup_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_0, 50, -60 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 1000);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_1, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_1, delay + 700 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_opacity );
lv_anim_start(&PropertyAnimation_1);

}

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_display_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_main_screen_init();
ui_startup_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_main);
}
