// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_main
void ui_main_screen_init(void);
lv_obj_t * ui_main;
lv_obj_t * ui_NavBar;
lv_obj_t * ui_classromLabel;
lv_obj_t * ui_clockContainer;
lv_obj_t * ui_clockLabel;
lv_obj_t * ui_timetableContainer;
lv_obj_t * ui_lessonBox;
lv_obj_t * ui_infoContainer2;
lv_obj_t * ui_circle2;
lv_obj_t * ui_Label2;
lv_obj_t * ui_moreInfoContainer2;
lv_obj_t * ui_topInfo1;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Label13;
lv_obj_t * ui_lessonBoxUnknown;
lv_obj_t * ui_infoContainer1;
lv_obj_t * ui_circle1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_moreInfoContainer1;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Label10;
lv_obj_t * ui_lessonBox1;
lv_obj_t * ui_infoContainer3;
lv_obj_t * ui_circle3;
lv_obj_t * ui_Label3;
lv_obj_t * ui_moreInfoContainer3;
lv_obj_t * ui_topInfo2;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Container4;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Container5;
lv_obj_t * ui_Label9;
lv_obj_t * ui_lessonBox2;
lv_obj_t * ui_infoContainer4;
lv_obj_t * ui_circle4;
lv_obj_t * ui_Label14;
lv_obj_t * ui_moreInfoContainer4;
lv_obj_t * ui_topInfo3;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Container6;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Container7;
lv_obj_t * ui_Label18;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_main_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_main);
}
