// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_main
void ui_main_screen_init(void);
extern lv_obj_t *ui_main;
extern lv_obj_t *ui_NavBar;
extern lv_obj_t *ui_classromLabel;
extern lv_obj_t *ui_clockContainer;
extern lv_obj_t *ui_clockLabel;
extern lv_obj_t *ui_timetableContainer;
extern lv_obj_t *ui_lessonBox;
extern lv_obj_t *ui_infoContainer2;
extern lv_obj_t *ui_circle2;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_moreInfoContainer2;
extern lv_obj_t *ui_topInfo1;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_lessonBoxUnknown;
extern lv_obj_t *ui_infoContainer1;
extern lv_obj_t *ui_circle1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_moreInfoContainer1;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_lessonBox1;
extern lv_obj_t *ui_infoContainer3;
extern lv_obj_t *ui_circle3;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_moreInfoContainer3;
extern lv_obj_t *ui_topInfo2;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Container4;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Container5;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_lessonBox2;
extern lv_obj_t *ui_infoContainer4;
extern lv_obj_t *ui_circle4;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_moreInfoContainer4;
extern lv_obj_t *ui_topInfo3;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_Container6;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_Container7;
extern lv_obj_t *ui_Label18;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// FONTS
LV_FONT_DECLARE( ui_font_H1);
LV_FONT_DECLARE( ui_font_P1);
LV_FONT_DECLARE( ui_font_h2);
LV_FONT_DECLARE( ui_font_h3);
LV_FONT_DECLARE( ui_font_p);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
