// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_red[1] = {0xD22232};
const ui_theme_variable_t _ui_theme_alpha_red[1] = {255};

const ui_theme_variable_t _ui_theme_color_lightgrayBG[1] = {0xD8D8D8};
const ui_theme_variable_t _ui_theme_alpha_lightgrayBG[1] = {255};

const ui_theme_variable_t _ui_theme_color_textGray[1] = {0x9CA3AF};
const ui_theme_variable_t _ui_theme_alpha_textGray[1] = {255};

const ui_theme_variable_t _ui_theme_color_teacherGray[1] = {0x606060};
const ui_theme_variable_t _ui_theme_alpha_teacherGray[1] = {255};

const ui_theme_variable_t _ui_theme_color_textTime[1] = {0x222021};
const ui_theme_variable_t _ui_theme_alpha_textTime[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

